# Generated by Django 3.0.6 on 2020-10-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20200624_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_record',
            name='item_quantity_after_sales',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sales_record',
            name='item_quantity_before_sales',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sales_record',
            name='item_quantity_sold',
            field=models.IntegerField(null=True),
        ),
    ]
