# Generated by Django 3.0.6 on 2020-10-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0011_auto_20201027_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_phone',
            field=models.CharField(max_length=13),
        ),
    ]
